steps:
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      [
        "cp",
        "gs://databasecamp-private/backend-infrastructure/service_account.json",
        "./service_account.json",
      ]
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      [
        "cp",
        "gs://databasecamp-private/backend-infrastructure/.env.develop",
        "./.env",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$TRIGGER_NAME", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$TRIGGER_NAME"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "$TRIGGER_NAME",
        "--image",
        "gcr.io/$PROJECT_ID/$TRIGGER_NAME",
        "--region",
        "asia-east1",
        "--platform",
        "managed",
        "--quiet",
      ]
images:
  - gcr.io/$PROJECT_ID/$TRIGGER_NAME
